require: rubocop-rspec

AllCops:
  Exclude:
      - 'db/schema.rb'
      - 'bin/*'
      - 'vendor/**/*'

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
Metrics/LineLength:
  Max: 199

RSpec/HookArgument:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false
